Extension factories and RdTextBuffer follower mode for c#.
JetBrains/rd pull request #211
Opened 2021-04-13 10:55 UTC by vvselischev

2021-04-20 09:14 UTC, ForNeVeR requested changes

2021-04-20 09:14 UTC, ForNeVeR commented on rd-kt/rd-gen/src/main/kotlin/com/jetbrains/rd/generator/nova/Members.kt
> +                    return delegate.factoryFqn ?: delegate.delegateFqn;
```suggestion
                    return delegate.factoryFqn ?: delegate.delegateFqn
```

2021-04-20 09:14 UTC, ForNeVeR commented on rd-kt/rd-gen/src/main/kotlin/com/jetbrains/rd/generator/nova/csharp/CSharp50Generator.kt
> +    protected open fun Member.ctorSubstitutedName(scope: Declaration) = when (this) {
Let's call this `creationExpressionSubstituted`? To avoid confusion between ctor name (without `new`) and this.

2021-04-20 09:14 UTC, ForNeVeR commented on rd-kt/rd-gen/src/main/kotlin/com/jetbrains/rd/generator/nova/csharp/CSharp50Generator.kt
> +    protected open val Member.Reactive.ctorSimpleName : String get () = when (this) {
And let's call this `simpleCreationExpression`.

2021-04-20 09:14 UTC, ForNeVeR commented
@nicklyu, could you please take a look at the `RdTextBuffer` changes?

2021-04-20 12:13 UTC, nicklyu approved these changes

2021-04-20 12:14 UTC, nicklyu commented
> @nicklyu, could you please take a look at the `RdTextBuffer` changes?
RdTextBuffer looks fine

2021-04-21 07:03 UTC, ForNeVeR approved these changes

2021-04-22 12:26 UTC, krasnotsvetov approved these changes

2021-04-22 13:13 UTC, merged