Extract RdContext into a base class to make value propert virtual
JetBrains/rd pull request #307
Opened 2022-05-25 21:55 UTC by nerzhulart

2022-05-26 10:30 UTC, ForNeVeR requested changes
In principle, LGTM. But let's wait for a review from @Iliya-usov.

2022-05-26 10:30 UTC, ForNeVeR commented on rd-kt/rd-gen/src/main/kotlin/com/jetbrains/rd/generator/nova/Types.kt
> -    fun context(type: INonNullableScalar) = append(Context.Generated(this, "", type)) {}
Could we please have an old function (which will delegate to `threadLocalContext`) as `@Deprecated`? Breaking changes are always very painful, and it's hard to apply them across all the codebase.

2022-05-27 07:13 UTC, ForNeVeR approved these changes

2022-05-27 13:22 UTC, Iliya-usov approved these changes

2022-05-30 08:36 UTC, merged