Replace BitHacks.Log2 with implementation based on de Bruijn sequence
JetBrains/rd pull request #408
Opened 2023-05-24 15:10 UTC by aloraman

Replace implementation of `BitHacks.Log2Floor` and `BitHacks.Log2Ceil` with more bit-hacky *de Bruijn multiplication*.
- smaller precomputed tables
- less instruction branching
- some test coverage

Further optimizations are possible:
- read precomputed table directly from assembly data without allocations (Requires `ReadOnlySpan<byte>` support, see https://github.com/dotnet/roslyn/pull/24621)
- use platform intrinsics (Requires runtime support), so software implementation can be replaced with hardware instruction (e.g. `Log2`, `LeadingZeroCount`, `BitScanReverse`, `MostSignificantBit`...)

2023-05-25 14:51 UTC, ulex requested changes

2023-05-25 16:53 UTC, aloraman commented on rd-net/Lifetimes/Util/BitHacks.cs
> +      return ourDeBruijnBitTable32[(int) ((value * DeBruijnSequence32) >> 27)];
Done!

2023-05-25 16:53 UTC, aloraman commented on rd-net/Lifetimes/Util/BitHacks.cs
> +      return ourDeBruijnBitTable64[(int) ((value * DeBruijnSequence64) >> 58)];
Ditto

2023-05-26 12:25 UTC, ulex approved these changes
Thank you so for your contribution and suggestions, @aloraman ! 
At the moment I see no way to use either ReadOnlySpan or runtime intrinsics: one of our targets is net35.
The proposed implementation is excellent for its purpose.
PS Thank you for giving me an opportunity to learn about De Bruijn multiplication

2023-05-26 12:26 UTC, merged